version: '3.8'

services:
  db:
    image: postgres:latest
    # Uncomment if you want to connect to db outside of docker
    # ports:
    #   - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: goodPassword
      POSTGRES_DB: summer
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    command: npm run start
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=student
      - DB_PASSWORD=goodPassword
      - DB_NAME=summer
    depends_on:
      - db

  frontend:
    build: ./frontend
    # Network mode work only in linux
    # network_mode: "host"
    ports:
      - "5173:5173"  # change for your frontend port

    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

    restart: always
    command: npm run host
    depends_on:
      - backend

  


volumes:
  db_data: