# version: '3.8'

services:
  db:
    image: postgres:latest
    # Uncomment if you want to connect to db outside of docker
    # ports:
    #   - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: goodPassword
      POSTGRES_DB: summer
    volumes:
      - db_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #     - ./pgadmin_config/servers.json:/pgadmin4/servers.json
  #   depends_on:
  #     - db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    # command: npm run start
    command: ["./wait-for-postgres.sh", "db", "npm", "run", "start"]

    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=student
      - DB_PASSWORD=goodPassword
      - DB_NAME=summer
      - JWT_SECRET=goodPassword
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
    depends_on:
      - db

  frontend:
    build: ./frontend
    # Network mode work only in linux
    # network_mode: "host"
    ports:
      - "5173:5173"  # change for your frontend port

    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

    restart: always
    command: npm run host
    depends_on:
      - backend

  


volumes:
  db_data:
  pgadmin_data: